# Generated by Django 2.1.7 on 2022-08-30 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220829_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 29, 21, 24, 21, 158960)),
        ),
    ]
